### ISSUE TITLE
field with append/prepend: Button not aligned with input in desktop browsers

### ISSUE THREAD

**Issue by CodeJosch** [GumbyFramework/Gumby#116]
A field with button appended/prepended just like on the gumby homepage is misaligned in Firefox, the input is positioned lower to the button see image (screenshot gumby homepage FF22):

![fieldappend](https://f.cloud.github.com/assets/925017/824799/3379426c-f052-11e2-8636-217f68111be6.png)

Other browsers have issues with the alignment as well:
- In Chrome28, the button is aligned a pixel too low.
- In IE9, the button is aligned a pixel too high.

**Possible fix for the FF issue:** Setting the buttons display to inline-block

in ui/_form.scss:167

``` css
&.prepend .btn, &.append .btn {
        a, input, button {
                padding: 0 12px;
                display:inline-block; /* added */
        }
}
```
