### ISSUE TITLE
Feature Request - Visibility Helper Classes

### ISSUE THREAD

**Issue by jafferhaider** [GumbyFramework/Gumby#27]
How about adding helper classes for hiding/showing elements based on media queries. Like the `hidden-desktop`, `hidden-tablet`, `hidden-phone` classes in Bootstrap (code pasted below).

``` css
.visible-phone {
  display: none !important;
}
.visible-tablet {
  display: none !important;
}
.hidden-desktop {
  display: none !important;
}
.visible-desktop {
  display: inherit !important;
}
@media (min-width: 768px) and (max-width: 979px) {
  .hidden-desktop {
    display: inherit !important;
  }
  .visible-desktop {
    display: none !important ;
  }
  .visible-tablet {
    display: inherit !important;
  }
  .hidden-tablet {
    display: none !important;
  }
}
@media (max-width: 767px) {
  .hidden-desktop {
    display: inherit !important;
  }
  .visible-desktop {
    display: none !important;
  }
  .visible-phone {
    display: inherit !important;
  }
  .hidden-phone {
    display: none !important;
  }
}
```
