### ISSUE TITLE
Blank White Box Rendering Issue on some Android Stock Browsers

### ISSUE THREAD

**Issue by PunchRockgroin** [GumbyFramework/Gumby#53]
Ran into an issue where on HTC Sense stock browsers a white box appears overlay elements at the top of the window, although this appears to be a rendering issue. This issue was traced to position:relative in the _grid.css for .column and .columns.

We used position:inherit in the moblie .column, .columns css on line 258 of _grid.scss

``` CSS
  .column, .columns {
    width: auto !important;
    float: none;
    margin-left: 0;
    margin-right: 0;
    position: inherit;
  }
```

Which seems to fix the issue, and has no apparent effects elsewhere on other mobile browsers at this time...
