### ISSUE TITLE
Difference between your CSS and my CSS generated

### ISSUE THREAD

**Issue by caouecs** [GumbyFramework/Gumby#76]
Hello,
when I compile gumby.scss on my system with the last master of Gumby, I have differences on gumby.css.

In your CSS, line 226 :

``` css
.sixteen.colgrid .row .one.column, .sixteen.colgrid .row .one.columns { width: 4.25532%; }
```

In my CSS :

``` css
.sixteen.colgrid .row .one.column { width: 4.25532%; }
```

I can resolve this problem and an another (line 175) when I remove in _grid.scss, line 110 to 112.

But I have others problems with buttons (line 486 to 517)

See : http://diffchecker.com/qz2xt6xe

Why have we these diffs ?

PS : I'm on Mac, I use Compass (v0.12.2) by command line.
