### ISSUE TITLE
Customizer includes everything even though we just want grid alone

### ISSUE THREAD

**Issue by tastycode** [GumbyFramework/Gumby#84]
We attempted to use the customizer to just get a grid framework. (Choosing Grid only) There are icon rules in the resulting CSS? We expected there to not be these rules, can we safely strip these out? e.g.

``` css
i.icon-download:before { content: ""; height: inherit; }
```
